-- ============================================================
-- SmartProperty 演示种子数据 - 系统基础库（由 scripts/seed/generate-seed.mjs 生成）
-- 场景：和家云物业 · 云栖湾小区（业务团队/账号/字典），幂等可重复执行
-- 业务用户密码统一为 Aa123456（BCrypt）
-- ============================================================
USE `smart_property_system`;
SET NAMES utf8mb4;

DELETE FROM sys_user WHERE id BETWEEN 2 AND 99;
DELETE FROM sys_user_role WHERE user_id > 1;
DELETE FROM sys_role WHERE id > 1;
DELETE FROM sys_dept WHERE id > 3;
DELETE FROM sys_dict_type WHERE id <= 99;
DELETE FROM sys_dict_data WHERE id <= 999;

INSERT INTO sys_dept (id, company_id, parent_id, dept_name, sort, status, create_by) VALUES
(4, 1, 1, '客服部', 3, 1, 'system'),
(5, 1, 1, '财务部', 4, 1, 'system'),
(6, 1, 1, '工程部', 5, 1, 'system'),
(7, 1, 1, '秩序维护部', 6, 1, 'system');

INSERT INTO sys_role (id, company_id, role_name, role_key, sort, status, create_by) VALUES
(2, 1, '物业经理', 'property_manager', 1, 1, 'system'),
(3, 1, '财务专员', 'finance_officer', 2, 1, 'system'),
(4, 1, '客服专员', 'customer_service', 3, 1, 'system'),
(5, 1, '维修工程师', 'maintenance_engineer', 4, 1, 'system'),
(6, 1, '秩序班长', 'security_squad', 5, 1, 'system');

INSERT INTO sys_user (id, company_id, dept_id, username, password, real_name, phone, phone_mask, gender, status, remark, create_by) VALUES
(2, 1, 1, 'zhangwm', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '张伟民', 'Af3BGPOV5zf9KBdtooQ3ww==', '139****1002', 1, 1, '物业经理', 'system'),
(3, 1, 5, 'wangyf', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '王雅芳', 'Mr/4Zp0zWUIgYvSw1dA92A==', '139****1003', 2, 1, '财务主管', 'system'),
(4, 1, 5, 'lichen', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '李晨', 'a0fgRPcmv9lPm8rM3uDVaw==', '139****1004', 2, 1, '会计', 'system'),
(5, 1, 4, 'liting', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '李婷', 'mEvVS928/iVmWNoo/QQeiA==', '139****1005', 2, 1, '客服主管', 'system'),
(6, 1, 4, 'zhouqian', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '周倩', 'bsWV3YLf8YMr9j4A/zygfQ==', '139****1006', 2, 1, '客服专员', 'system'),
(7, 1, 6, 'liuzg', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '刘志刚', 'e8xWWYLbqhI0ZPrFnq9Xjw==', '139****1007', 1, 1, '维修工程师', 'system'),
(8, 1, 6, 'sunjj', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '孙建军', 'Sefa50gAS4qR3vd7edSOCw==', '139****1008', 1, 1, '水电工', 'system'),
(9, 1, 7, 'zhaotj', '$2a$10$HudK2dk5PYP7CJ1UQBxfBOWyrnDrVtak304mExjvwwbk/OpLyJhKi', '赵铁军', '5BiFENtcbWl1PNicb5Go8g==', '139****1009', 1, 1, '秩序班长', 'system');

INSERT INTO sys_user_role (user_id, role_id) VALUES
(2, 2),
(3, 3),
(4, 3),
(5, 4),
(6, 4),
(7, 5),
(8, 5),
(9, 6);

INSERT INTO sys_dict_type (id, dict_name, dict_type, status, remark, create_by) VALUES
(1, '工单类型', 'order_type', 1, '服务工单类型', 'system'),
(2, '工单优先级', 'order_priority', 1, NULL, 'system'),
(3, '支付方式', 'pay_type', 1, NULL, 'system'),
(4, '收费模式', 'charge_mode', 1, NULL, 'system'),
(5, '仪表类型', 'meter_type', 1, NULL, 'system'),
(6, '系统开关状态', 'sys_normal_disable', 1, NULL, 'system'),
(7, '用户性别', 'sys_user_sex', 1, NULL, 'system'),
(8, '房间状态', 'room_status', 1, NULL, 'system'),
(9, '房间类型', 'room_type', 1, NULL, 'system'),
(10, '装修标准', 'room_decoration', 1, NULL, 'system'),
(11, '楼宇类型', 'building_type', 1, NULL, 'system'),
(12, '业主类型', 'owner_type', 1, NULL, 'system'),
(13, '装修进度状态', 'decoration_status', 1, NULL, 'system'),
(14, '押金状态', 'deposit_status', 1, NULL, 'system'),
(15, '验房状态', 'check_status', 1, NULL, 'system'),
(16, '验房类型', 'check_type', 1, NULL, 'system'),
(17, '验房结果', 'check_result', 1, NULL, 'system'),
(18, '租赁合同状态', 'lease_status', 1, NULL, 'system'),
(19, '租赁类型', 'lease_type', 1, NULL, 'system'),
(20, '缴费周期', 'pay_cycle', 1, NULL, 'system'),
(21, '费项类型', 'fee_type', 1, NULL, 'system'),
(22, '账单周期', 'billing_cycle', 1, NULL, 'system'),
(23, '账单状态', 'ledger_status', 1, NULL, 'system'),
(24, '缴费记录状态', 'payment_status', 1, NULL, 'system'),
(25, '预收款状态', 'prepayment_status', 1, NULL, 'system'),
(26, '车位类型', 'parking_type', 1, NULL, 'system'),
(27, '车位状态', 'parking_status', 1, NULL, 'system'),
(28, '票据类型', 'invoice_type', 1, NULL, 'system'),
(29, '票据状态', 'invoice_status', 1, NULL, 'system'),
(30, '操作类型', 'oper_type', 1, NULL, 'system'),
(31, '登录/操作结果', 'sys_common_status', 1, NULL, 'system');

INSERT INTO sys_dict_data (id, dict_type, dict_label, dict_value, sort, status, create_by) VALUES
(1, 'order_type', '报修', 1, 1, 1, 'system'),
(2, 'order_type', '投诉', 2, 2, 1, 'system'),
(3, 'order_type', '建议', 3, 3, 1, 'system'),
(4, 'order_type', '咨询', 4, 4, 1, 'system'),
(5, 'order_priority', '紧急', 1, 1, 1, 'system'),
(6, 'order_priority', '普通', 2, 2, 1, 'system'),
(7, 'order_priority', '低', 3, 3, 1, 'system'),
(8, 'pay_type', '现金', 1, 1, 1, 'system'),
(9, 'pay_type', '转账', 2, 2, 1, 'system'),
(10, 'pay_type', '微信', 3, 3, 1, 'system'),
(11, 'pay_type', '支付宝', 4, 4, 1, 'system'),
(12, 'pay_type', '预收款', 5, 5, 1, 'system'),
(13, 'charge_mode', '按面积', 1, 1, 1, 'system'),
(14, 'charge_mode', '按户', 2, 2, 1, 'system'),
(15, 'charge_mode', '按用量', 3, 3, 1, 'system'),
(16, 'meter_type', '水表', 1, 1, 1, 'system'),
(17, 'meter_type', '电表', 2, 2, 1, 'system'),
(18, 'meter_type', '气表', 3, 3, 1, 'system'),
(19, 'sys_normal_disable', '停用', 0, 1, 1, 'system'),
(20, 'sys_normal_disable', '正常', 1, 2, 1, 'system'),
(21, 'sys_user_sex', '未知', 0, 1, 1, 'system'),
(22, 'sys_user_sex', '男', 1, 2, 1, 'system'),
(23, 'sys_user_sex', '女', 2, 3, 1, 'system'),
(24, 'room_status', '空置', 1, 1, 1, 'system'),
(25, 'room_status', '已售', 2, 2, 1, 'system'),
(26, 'room_status', '已租', 3, 3, 1, 'system'),
(27, 'room_status', '装修中', 4, 4, 1, 'system'),
(28, 'room_type', '住宅', 1, 1, 1, 'system'),
(29, 'room_type', '商业', 2, 2, 1, 'system'),
(30, 'room_type', '办公', 3, 3, 1, 'system'),
(31, 'room_type', '仓库', 4, 4, 1, 'system'),
(32, 'room_type', '车库', 5, 5, 1, 'system'),
(33, 'room_decoration', '毛坯', 1, 1, 1, 'system'),
(34, 'room_decoration', '简装', 2, 2, 1, 'system'),
(35, 'room_decoration', '精装', 3, 3, 1, 'system'),
(36, 'building_type', '住宅', 1, 1, 1, 'system'),
(37, 'building_type', '商业', 2, 2, 1, 'system'),
(38, 'building_type', '办公', 3, 3, 1, 'system'),
(39, 'building_type', '仓库', 4, 4, 1, 'system'),
(40, 'building_type', '车库', 5, 5, 1, 'system'),
(41, 'owner_type', '个人', 1, 1, 1, 'system'),
(42, 'owner_type', '企业', 2, 2, 1, 'system'),
(43, 'decoration_status', '申请中', 1, 1, 1, 'system'),
(44, 'decoration_status', '施工中', 2, 2, 1, 'system'),
(45, 'decoration_status', '已完工', 3, 3, 1, 'system'),
(46, 'decoration_status', '已验收', 4, 4, 1, 'system'),
(47, 'deposit_status', '未缴', 1, 1, 1, 'system'),
(48, 'deposit_status', '已缴', 2, 2, 1, 'system'),
(49, 'deposit_status', '已退', 3, 3, 1, 'system'),
(50, 'check_status', '待处理', 1, 1, 1, 'system'),
(51, 'check_status', '已整改', 2, 2, 1, 'system'),
(52, 'check_type', '物业验房', 1, 1, 1, 'system'),
(53, 'check_type', '业主验房', 2, 2, 1, 'system'),
(54, 'check_result', '合格', 1, 1, 1, 'system'),
(55, 'check_result', '不合格', 2, 2, 1, 'system'),
(56, 'lease_status', '草稿', 1, 1, 1, 'system'),
(57, 'lease_status', '生效', 2, 2, 1, 'system'),
(58, 'lease_status', '已终止', 3, 3, 1, 'system'),
(59, 'lease_status', '已到期', 4, 4, 1, 'system'),
(60, 'lease_type', '整租', 1, 1, 1, 'system'),
(61, 'lease_type', '分租', 2, 2, 1, 'system'),
(62, 'pay_cycle', '月付', 1, 1, 1, 'system'),
(63, 'pay_cycle', '季付', 2, 2, 1, 'system'),
(64, 'pay_cycle', '半年付', 3, 3, 1, 'system'),
(65, 'pay_cycle', '年付', 4, 4, 1, 'system'),
(66, 'fee_type', '常规', 1, 1, 1, 'system'),
(67, 'fee_type', '公摊', 2, 2, 1, 'system'),
(68, 'fee_type', '临时', 3, 3, 1, 'system'),
(69, 'fee_type', '临客', 4, 4, 1, 'system'),
(70, 'billing_cycle', '月', 1, 1, 1, 'system'),
(71, 'billing_cycle', '季', 2, 2, 1, 'system'),
(72, 'billing_cycle', '半年', 3, 3, 1, 'system'),
(73, 'billing_cycle', '年', 4, 4, 1, 'system'),
(74, 'ledger_status', '未收', 1, 1, 1, 'system'),
(75, 'ledger_status', '部分收', 2, 2, 1, 'system'),
(76, 'ledger_status', '已收', 3, 3, 1, 'system'),
(77, 'payment_status', '正常', 1, 1, 1, 'system'),
(78, 'payment_status', '已退款', 2, 2, 1, 'system'),
(79, 'payment_status', '已作废', 3, 3, 1, 'system'),
(80, 'prepayment_status', '正常', 1, 1, 1, 'system'),
(81, 'prepayment_status', '已退款', 2, 2, 1, 'system'),
(82, 'parking_type', '地上', 1, 1, 1, 'system'),
(83, 'parking_type', '地下', 2, 2, 1, 'system'),
(84, 'parking_type', '机械', 3, 3, 1, 'system'),
(85, 'parking_status', '空闲', 1, 1, 1, 'system'),
(86, 'parking_status', '已售', 2, 2, 1, 'system'),
(87, 'parking_status', '已租', 3, 3, 1, 'system'),
(88, 'invoice_type', '收据', 1, 1, 1, 'system'),
(89, 'invoice_type', '发票', 2, 2, 1, 'system'),
(90, 'invoice_status', '未使用', 1, 1, 1, 'system'),
(91, 'invoice_status', '已使用', 2, 2, 1, 'system'),
(92, 'invoice_status', '已作废', 3, 3, 1, 'system'),
(93, 'oper_type', '其它', 0, 1, 1, 'system'),
(94, 'oper_type', '新增', 1, 2, 1, 'system'),
(95, 'oper_type', '修改', 2, 3, 1, 'system'),
(96, 'oper_type', '删除', 3, 4, 1, 'system'),
(97, 'oper_type', '查询', 4, 5, 1, 'system'),
(98, 'oper_type', '导出', 5, 6, 1, 'system'),
(99, 'sys_common_status', '失败', 0, 1, 1, 'system'),
(100, 'sys_common_status', '成功', 1, 2, 1, 'system');

